{% set version = "0.18" %}

package:
  name: isl
  version: {{ version }}

source:
  fn: isl-{{ version }}.tar.bz2
  url: http://isl.gforge.inria.fr/isl-{{ version }}.tar.bz2
  md5: 11436d6b205e516635b666090b94ab32

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - gmp >=5.0.1,<7
  run:
    - gmp >=5.0.1,<7

test:
  commands:
    - test -f "$PREFIX/lib/libisl.a"
    - test -f "$PREFIX/lib/libisl.la"
    - test -f "$PREFIX/lib/libisl.so"  # [linux]
    - test -f "$PREFIX/lib/libisl.dylib"  # [osx]
    - test -d "$PREFIX/include/isl"

about:
  home: http://isl.gforge.inria.fr/
  license: MIT
  summary: a thread-safe C library for manipulating sets and relations of integer points bounded by affine constraints.

extra:
  recipe-maintainers:
    - frol
