{% set version = "0.28" %}

package:
  name: isl
  version: {{ version }}

source:
  fn: isl-{{ version }}.tar.xz
  url: https://libisl.sourceforge.io/isl-{{ version }}.tar.xz
  sha256: 3dc31b8e1b18329e42d5dfbf84dd55e15c59b61569a2ab246f61497d9592f727
  patches:
    # From https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-isl/isl-0.14.1-no-undefined.patch
    - no_undefined.patch  # [win]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("isl", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - libtool  # [unix]
    - autotools_clang_conda  # [win]
    - make  # [unix]
    - m2-patch  # [win]

test:
  commands:
    - if not exist %LIBRARY_LIB%\\isl.lib exit 1  # [win]
    - if not exist %LIBRARY_INC%\\isl\\options.h exit 1  # [win]
    - test ! -f "$PREFIX/lib/libisl.a"  # [unix]
    - test -f "$PREFIX/lib/libisl${SHLIB_EXT}"  # [unix]
    - test -d "$PREFIX/include/isl"  # [unix]

about:
  home: https://libisl.sourceforge.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: a thread-safe C library for manipulating sets and relations of integer points bounded by affine constraints.
  description: |
    isl is a thread-safe C library for manipulating sets and relations of integer
    points bounded by affine constraints. It is used as the polyhedral loop
    optimizer (Graphite) backend in GCC and by related compiler toolchain packages.
  dev_url: https://repo.or.cz/isl.git
  doc_url: https://libisl.sourceforge.io/user.html

extra:
  recipe-maintainers:
    - frol
    - isuruf
