{% set version = "0.22.1" %}

package:
  name: isl
  version: {{ version }}

source:
  fn: isl-{{ version }}.tar.xz
  url: https://libisl.sourceforge.io/isl-{{ version }}.tar.xz
  sha256: 28658ce0f0bdb95b51fd2eb15df24211c53284f6ca2ac5e897acc3169e55b60f
  patches:
    # From https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-isl/isl-0.14.1-no-undefined.patch
    - no_undefined.patch  # [win]

build:
  number: 3
  run_exports:
    - {{ pin_subpackage("isl", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libtool                # [unix]
    - autotools_clang_conda  # [win]
    - make                   # [unix]
    - m2-patch    # [win]
 
test:
  commands:
    - if not exist %LIBRARY_LIB%\\isl.lib exit 1            # [win]
    - if not exist %LIBRARY_INC%\\isl\\options.h exit 1     # [win]
    - test ! -f "$PREFIX/lib/libisl.a"          # [unix]
    - test -f "$PREFIX/lib/libisl${SHLIB_EXT}"  # [unix]
    - test -d "$PREFIX/include/isl"             # [unix]

about:
  home: http://isl.gforge.inria.fr/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: a thread-safe C library for manipulating sets and relations of integer points bounded by affine constraints.

extra:
  recipe-maintainers:
    - frol
    - isuruf
