travis:
  secure:
    BINSTAR_TOKEN: YkwPa3E++OUcK9+NIpDKKO7Rx6m/L3JmpFAaAf8NSTGAh3WW/MU2QPJlMz6bkhs1OErFV62bPAdpw3sP6Lqzg1h77Wy4ytpHI2OpTiTd4eUN6SHe90//meljmE1TU2eZQ/68KxcXYJooaXSazD/X29yCwHyVrFlfpzWS6Yhilsi6+tx0i4h5CIWv+G+nxrr3gErTBeLsDKMKZ8+Bl18LAJWFmJKwaJirqln3SWIkj4cWTtmfF2SpmduwZBLoo+9QFNi85E8e0L4DUlby3tks25vgt8l7qUtHh13GdfwKwRtd6jTrP08ZoKISsGDEn1OVCD/Q+89eyAz2Ul6YY6HdRjGskonEPVETCJtGkx1smOBL1Le9LsX2UyqTLKZ882ERAWJpQrxdt9qJ2BsITKgMLZxRzq1eC1MfOKPz2QjXJznturvnoKprvGIYp3xEDtSJPMlz4yp12L870r6e03zq3iHthsqeisYGUwpYQdKYOJj5LTy8FKg/iWR+clxOTc4dzOL8gWeFLB0MgJiyLM2fxbtQfXD0+tTOMCRpAEBTPYWZweeDBm8YiOYyDmOyKts1GCNOWCT101vMNEdGkeLOFSw6SjY3Szk0x2xIu/QJgmCyrDzpvfpGhd82IYR1CIpDA2tCxgfgJlsOmebjk5bO5N6zivBDDSz/tARciGijkcc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
