travis:
  secure:
    BINSTAR_TOKEN: fSZ21IMfoGVS4/DGNo3VXg1GDCNhCp9zSP95fUspPL2eG963ODFuSJhtA7M5uZZhvjArNpA01jXkxRI0hsAZ3wOhAfCfq59BjUVUm3xWRD2VQl7Um7mtWD7Dk8BkzitzKEWYsMFJ+SwyvcBwLthxmtbMGOcnGAVGbc2g13fh0JsuEXAWAO6GEddl2BES9Y2Z5P9V6jQhVxdQ8ANARtbbii6KGl4VsCHdB3wkX43fLeKmD3HapeQcoUFk5+XUHTDchYQM90JAUQ5IEKu0bCbJt/CQlJVuQUS3UxZsVs3e5sN0saBoBAvpogLggazGaH7s8Q58JCAe5/byRlZQUZJJhIuR2XhQAIrssWpVW/YDEOgpScpzTz4nS+tGygONCOKL2zQ7rswykBomyAv4d1ftzyMrw/dWJ+r6ZMMg+Jzq+mgN5pqDDcPsqr5ZMwaPtH0LZYmqjCix80YmF9CUpQiFx+kTsna70hlgyxrJoIy90EINeImU98jn4DB4SUgTQ2LCbYFWjffY0bt9DMBwbVtGSPqvS7SIJF0E/2o2aVDwYQHmkZUVHTa78D8Sm+NVryynjZvnZzlqKWvA+R1rPj8GvO92dBlIDnJxJyYDJ01jEV/oCockgC9TusERSLDci21mrwoXDlziy0RsvYTTEgIPFSkQIQsG/J+O7ltazeBYVhE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
